### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by JamesColinClark** [porrey/ledmatrixide#1]
When I upload some pictures into the program, I receive an Exception error:

Exception
Index and length must refer to a location within the string.
Parameter name: length

How can I resolve this issue?  It doesn't do this with all pictures.  Is this something I can resolve by adjusting the pictures?

![Exception](https://user-images.githubusercontent.com/37080227/97118573-529d9600-16d0-11eb-8b85-36d5653113cc.jpg)

**Comment by porrey** [comment]
If you can provide some images that fail I can run some tests. Also provide details necessary to reproduce the issue.

**Comment by JamesColinClark** [comment]
I can't figure out why some pictures work and some don't.  Most of the pictures I have don't work.  I've tried resizing, renaming, saving as different file types.  Can't figure it out.

Let's see.  Some details:
I am using Windows 10 Home Edition.  64 bit.
Visual Studio 2019 to build and deploy.
Intel Core i7 7700K @ 4.20GHz
ASUS Prime Z270-P Motherboard
64 GB DDR4 3200
Gigabyte NVIDIA GeForce RTX 2070

Anything in particular that you need?

![Smiley Thumbs Up Emoji](https://user-images.githubusercontent.com/37080227/97130083-0705df00-1706-11eb-8bf6-93e583ee1492.jpg)

![Goatskin Leggings](https://user-images.githubusercontent.com/37080227/97130324-bf338780-1706-11eb-9a36-0222ffc30f69.jpg)

![R1200GS in sand](https://user-images.githubusercontent.com/37080227/97130870-3d445e00-1708-11eb-8abb-d3fe592dabc1.jpg)

**Comment by porrey** [comment]
Thanks for the detail. I was able to reproduce the issue with the images above.

The app is using the Camera property to store details about the image. It was failing to check if the property was an empty string. This has been corrected.

Please let me know if this resolves your issue.

**Comment by JamesColinClark** [comment]
Issue Resolved.  Works great now.  Thank you for your amazing response to this.
